train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BS)"
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BS)"
  - _target_: src.metrics.BeamSearchLMCERMetric
    name: "CER_(BS_LM)"
  - _target_: src.metrics.BeamSearchLMWERMetric
    name: "WER_(BS_LM)"