defaults:
  - model: deepspeech2
  - metrics: base
  - datasets: inference # we do not want to run inference on training data
  - dataloader: base
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "resuly" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "/kaggle/input/model-best-3/model_best_3.pth" # path to the pretrained model
