defaults:
  - model: deepspeech2
  - metrics: base
  - datasets: inference_other # we do not want to run inference on training data
  - dataloader: base
  - transforms: base_only_instance
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_lm: True
  kenlm_model_path: "/kaggle/input/3-gram-model/3-gram.arpa"
  vocab_path: "/kaggle/input/vocabulary/librispeech-vocab.txt"

inferencer:
  device_tensors: [ "spectrogram", "text_encoded" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "result" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "/kaggle/input/model-best-3/model_best_3.pth" # path to the pretrained model
