train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 512
  audio: # name of the tensor on which we apply transform
    _target_: src.transforms.RandomApply
    p: 1.0
    transforms:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: src.transforms.wav_augs.Gain
          p: 0.1
          min_gain_in_db: -3.0
        - _target_: src.transforms.wav_augs.ColoredNoise
          p: 0.1
          sample_rate: 16000
          min_snr_in_db: 15.0
          max_snr_in_db: 20.0
        - _target_: src.transforms.wav_augs.BandPass
          p: 0.1
          sample_rate: 16000
          min_center_frequency: 1900
          max_center_frequency: 2100
        - _target_: src.transforms.wav_augs.BandStop
          p: 0.1
          sample_rate: 16000
          min_center_frequency: 1900
          max_center_frequency: 2100
        - _target_: src.transforms.wav_augs.PeakNormalize
          p: 0.1
          sample_rate: 16000
        - _target_: src.transforms.wav_augs.PitchShifting
          p: 0.1
          sample_rate: 16000
          min_transpose_semitones: -1.0
          max_transpose_semitones: 1.0
        - _target_: src.transforms.wav_augs.Shifting
          p: 0.1
          sample_rate: 16000
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 512
