train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 512
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        p: 0.1
      - _target_: src.transforms.wav_augs.ColoredNoise
        p: 0.1
        min_snr_in_db: 10
        max_snr_in_db: 20
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.BandPass
        p: 0.1
        sample_rate: 16000
        min_bandwidth_fraction: 1.1 
        min_center_frequency: 1900
        max_center_frequency: 2100
      - _target_: src.transforms.wav_augs.BandStop
        p: 0.1
        sample_rate: 16000
        max_bandwidth_fraction: 1.2
        min_center_frequency: 1900
        max_center_frequency: 2100
      - _target_: src.transforms.wav_augs.Shifting
        p: 0.1
        sample_rate: 16000
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 512
